#!/bin/sh
CC=mpic++
N="${N-2}"
if test -f $TARGET.cc
then
  echo "  >>> COMPILE[ $TARGET ] BEG <<<"
  $CC -DELAI_USE_MPI -DELAI_DEBUG -o $TARGET -I../Elai $TARGET.cc
  ret=$?
  echo "  >>> COMPILE[ $TARGET ] END <<<"
  if test 0 -eq $ret
  then
    echo "!!    COMPILE SUCCEEDED"
    echo
    echo "  >>> CHECK[ $TARGET ] BEG <<<"
    mpiexec -n $N ./$TARGET
    ret=$?
    rm $TARGET
    echo "  >>> CHECK[ $TARGET ] END <<<"
    if test 0 -eq $ret
    then
      echo "!!    CHECK SUCCEEDED"
      echo
    else
      echo "!!    CHECK FAILED"
      echo
      exit 1
    fi
  else
    echo "!!    COMPILE FAILED"
    echo
    exit 1
  fi
fi
