#!/bin/sh
if test -f $TARGET.cc
then
  echo "  >>> COMPILE[ $TARGET ] BEG <<<"
  c++ -DELAI_DEBUG -pg -o $TARGET -I../Elai $TARGET.cc
  ret=$?
  echo "  >>> COMPILE[ $TARGET ] END <<<"
  if test 0 -eq $ret
  then
    echo "!!    COMPILE SUCCEEDED"
    echo
    echo "  >>> CHECK[ $TARGET ] BEG <<<"
    ./$TARGET
    gprof ./$TARGET gmon.out
    ret=$?
    echo "  >>> CHECK[ $TARGET ] END <<<"
    if test 0 -eq $ret
    then
      echo "!!    CHECK SUCCEEDED"
      echo
    else
      echo "!!    CHECK FAILED"
      echo
      exit 1
    fi
  else
    echo "!!    COMPILE FAILED"
    echo
    exit 1
  fi
fi
